use core::str::FromStr;

// === Type definitions ===

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
/// Represents a "routing" exchange where orders and market data requests can be directed.
pub enum Routing {
    /// IBKR's "SMART" rouring destination, which aggregtes data from many component exchanges
    /// and intelligently routes orders to minimize overall costs net of rebates.
    Smart,
    /// A physical exchange like NYSE or NASDAQ.
    Primary(Primary),
}

#[derive(Debug, Default, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
/// An error type returned when a given exchange code cannot be matched with a valid
/// [`Primary`] or [`Routing`] exchange.
pub struct ParseExchangeError(pub String);

impl std::fmt::Display for ParseExchangeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Invalid exchange {}", self.0)
    }
}

impl std::error::Error for ParseExchangeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }

    fn description(&self) -> &str {
        "description() is deprecated; use Display"
    }

    fn cause(&self) -> Option<&dyn std::error::Error> {
        self.source()
    }
}

// Docs here would be somewhat ridiculous
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
/// Represents all the valid physicsal trading venues for various contracts.
pub enum Primary {
    AmsterdamseEffectenbeurs,
    AlphaTradingSystems,
    AmericanStockExchange,
    ApexEuronext,
    ApexItaly,
    AquisExchangeEuropeGermany,
    AquisExchangeEuropeEuronext,
    AquisExchangeEuropeSpain,
    AquisExchangeEuropeItaly,
    Quadriserv,
    Archipelago,
    Arcaedge,
    AustralianStockExchange,
    AsxCentrePoint,
    BarclaysGovernmentBonds,
    BatsTradingInc,
    BelgianFuturesAmpOptionsExchange,
    NasdaqOmxBx,
    Bloomberg,
    BolsaDeMadrid,
    Bond1GovernmentBonds,
    BondDesk,
    BonddeskForUsGovernmentSecurities,
    BondDeskMunicipalBonds,
    GovernmentBondsLargeOrders,
    BostonOptionExchange,
    BudapestStockExchange,
    LisbonStockExchange,
    BorsaValoriDiMilano,
    BorsaItalianaEtf,
    BatsYExchange,
    CommerzbankAgFrankfurtCurrencyDealing2,
    CommerzbankAgFrankfurtCurrencyDealing,
    ChicagoBoardOptionsExchange,
    CboeJapanLimited,
    ChicagoBoardOptionsExchange2,
    ChicagoBoardOfTrade,
    CanadianDerivativesExchange,
    CboeFuturesExchange,
    ChicagoFuturesExchangeTradingAtSettlement,
    ChinextSharesOnShenzhenStockExchange,
    ChiXCanadaAtsLimited,
    ChiXAustralia,
    ChicagoStockExchange,
    CitibankCurrencyDealing,
    ChicagoMercantileExchange,
    CommodityExchange,
    CopenhagenStockExchange,
    CreditSuisseGovernmentBondsSmallOrders,
    CsfbAlgorithmicEngine,
    CreditSuisseCurrencyDealing,
    CitadelZeroCommission,
    DirectEdgeEcnLlc,
    CboeGermany,
    CboeEuronext,
    CboeSpain,
    CboeEuropeBVDxeOrderBookItaly,
    ElektronischeBoerseSchweiz,
    DirectEdgeEcnEdgea,
    BatsTradingEdgx,
    MiaxEmeraldExchange,
    IceEndexFutures,
    EuronextBelgium,
    InternalFractionalShareVenueForEuStocksAndEtfs,
    IbEuropeanSystematicInternaliser,
    EurexBritishMarketsForLchCrestClearing,
    FoxRiver,
    PartnerFractionalShares,
    FinancieleTermijnmarktAmsterdam,
    Finra,
    MutualFundHoldingVenue,
    FrankfurterWertpapierboerse,
    NonStandardSettlementForFx,
    IseGemini,
    BRseMNchenAg,
    BRseMNchenAgForCblSettlement,
    GoldmanSachsCurrencyDealing,
    GoldmanSachsCurrencyDealing2,
    HeadlandsTechnologies,
    HeadlandsTechnologiesMunis,
    HelsinkiStockExchange,
    HongKongFuturesExchange,
    HsbcCurrencyDealing,
    HsbcCurrencyDealing2,
    HartfieldTitusAndDonnelly,
    IbCfdDealingAsiaPacific,
    InteractiveBrokersBond,
    InteractiveBrokersCommodity,
    IbDarkPool,
    IbkrOvernightExchange,
    IbCurrencyDealing,
    IbFxCfdDealing,
    IntegriertesBoersenhandelsUndInformationsSystem,
    InteractiveBrokersAssetManagement,
    IbkrNote,
    InternalizedTradingOfMetals,
    IbCfdDealingUs,
    IbUsOpt,
    IceCryptocurrency,
    IceFuturesUsInc,
    InteractiveBrokersDealingSystem,
    IbForexPro,
    IdealCurrencyDealing,
    ItalianDerivativesMarketMilano,
    InvestorsExchange,
    InternationalPetroleumExchange,
    InterestRateRecordingExchange,
    InternationalSecuritiesExchange,
    Island,
    JaneStreetExecutionServices,
    JaneStreetZeroCommission,
    JefferiesAlgorithmicEngine,
    JpmcCorporateBonds,
    Japannext,
    KoreaStockExchange,
    LongTermStockExchange,
    MarcheATermeDInstrumentsFinanciers,
    MercadoEspanolDeFuturosFinancierosRentaVariableProxy,
    MembersExchange,
    IseMercury,
    MercadoMexicanoDeDerivados,
    MexicoStockExchange,
    MiamiOptionsExchange,
    MillenniumAdvisorsCorporateBonds,
    MarketaxessCorporates,
    MarcheDesOptsNegDeLaBourseDeParis,
    MorganStanleyCurrencyDealing,
    NasdaqRiga,
    NasdaqTallinn,
    AbNasdaqVilnius,
    NationalAssociationOfSecurityDealers,
    NasdaqOmxBxOptionsExchange,
    NationalAssociationOfSecurityDealersOptionsMarket,
    NatixisCurrencyDealing,
    KnightTradingOtcbbAndPinkSheets,
    IbkrRetailZeroCommission,
    NationalStockExchangeOfIndiaLimited,
    NewYorkBoardOfTrade,
    NewYorkMercantileExchange,
    NewYorkStockExchange,
    NyseFloor,
    NyseLiffeUs,
    NyseNational,
    OmegaAts,
    StockholmOptionsMarket,
    NorwegianSharesOnOmx,
    OsloStockExchange,
    OsakaStockExchange,
    OslCryptoExchange,
    OtcBulletinBoard,
    OtcLinkEcn,
    OvernightTrading,
    PaxosCryptoExchange,
    MiaxPearlExchange,
    PhiladelphiaStockExchange,
    PinkSheets,
    PraqueStockExchange,
    PacificStockExchange,
    NasdaqOmxPsx,
    PureTrading,
    RoyalBankOfCanadaCurrencyDealing2,
    RoyalBankOfCanadaCurrencyDealing,
    RoyalBankOfScotlandCurrencyDealing,
    ExchangeForRussellIndices,
    StockExchangeOfHongKong,
    StockExchangeHongKongNorthboundTradingLink,
    HongKongShenzhenStockExchangeNorthboundTradingLink,
    StockholmFondbors,
    SingaporeExchange,
    SingaporeExchangeCme,
    TheSmallExchange,
    SydneyFuturesExchange,
    SumridgePartners,
    SumridgePartnersMunicipalBonds,
    StuttgartWertpapierboerse,
    TelAvivStockExchange,
    Tradegate,
    TurquoiseGlobalHoldingsEuropeBVGermany,
    TurquoiseGlobalHoldingsEuropeBVEuronext,
    TurquoiseGlobalHoldingsEuropeBVSpain,
    TurquoiseGlobalHoldingsBVItaly,
    ThFxCfdDealing,
    TPlusOne,
    TradewebCorporate,
    TradewebGovernment,
    TorontoStockExchange,
    TokyoStockExchange,
    UbsCurrencyDealing,
    UbsCorporateBond,
    UbsCurrencyDealing2,
    KnightValuebondCorporate,
    KnightValuebondGovernment,
    MunicipalBondsOnValuebond,
    TsxVentureExchange,
    VirtuFinancialGovernmentBonds,
    ViennaStockExchange,
    WellsFargoForex,
    WarsawStockExchange,
}

// === Type implementations ===

impl FromStr for Routing {
    type Err = ParseExchangeError;

    #[inline]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s.to_uppercase().as_str() {
            "SMART" => Self::Smart,
            prim => Self::Primary(prim.parse()?),
        })
    }
}

impl ToString for Routing {
    fn to_string(&self) -> String {
        match *self {
            Self::Smart => "SMART".to_owned(),
            Self::Primary(prim) => prim.to_string(),
        }
    }
}

impl FromStr for Primary {
    type Err = ParseExchangeError;

    #[allow(clippy::too_many_lines)]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s.to_uppercase().as_str() {
            "AEB" => Self::AmsterdamseEffectenbeurs,
            "ALPHA" => Self::AlphaTradingSystems,
            "AMEX" => Self::AmericanStockExchange,
            "APEXEN" => Self::ApexEuronext,
            "APEXIT" => Self::ApexItaly,
            "AQEUDE" => Self::AquisExchangeEuropeGermany,
            "AQEUEN" => Self::AquisExchangeEuropeEuronext,
            "AQEUES" => Self::AquisExchangeEuropeSpain,
            "AQEUIT" => Self::AquisExchangeEuropeItaly,
            "AQS" => Self::Quadriserv,
            "ARCA" => Self::Archipelago,
            "ARCAEDGE" => Self::Arcaedge,
            "ASX" => Self::AustralianStockExchange,
            "ASXCEN" => Self::AsxCentrePoint,
            "BARCBONDG" => Self::BarclaysGovernmentBonds,
            "BATS" => Self::BatsTradingInc,
            "BELFOX" => Self::BelgianFuturesAmpOptionsExchange,
            "BEX" => Self::NasdaqOmxBx,
            "BLOOMBERG" => Self::Bloomberg,
            "BM" => Self::BolsaDeMadrid,
            "BOND1G" => Self::Bond1GovernmentBonds,
            "BONDDESK" => Self::BondDesk,
            "BONDDESKG" => Self::BonddeskForUsGovernmentSecurities,
            "BONDDESKM" => Self::BondDeskMunicipalBonds,
            "BONDLARGE" => Self::GovernmentBondsLargeOrders,
            "BOX" => Self::BostonOptionExchange,
            "BUX" => Self::BudapestStockExchange,
            "BVL" => Self::LisbonStockExchange,
            "BVME" => Self::BorsaValoriDiMilano,
            "BVME.ETF" => Self::BorsaItalianaEtf,
            "BYX" => Self::BatsYExchange,
            "CBK2FX" => Self::CommerzbankAgFrankfurtCurrencyDealing2,
            "CBKFX" => Self::CommerzbankAgFrankfurtCurrencyDealing,
            "CBOE" => Self::ChicagoBoardOptionsExchange,
            "CBOE.JPN" => Self::CboeJapanLimited,
            "CBOE2" => Self::ChicagoBoardOptionsExchange2,
            "CBOT" => Self::ChicagoBoardOfTrade,
            "CDE" => Self::CanadianDerivativesExchange,
            "CFE" => Self::CboeFuturesExchange,
            "CFETAS" => Self::ChicagoFuturesExchangeTradingAtSettlement,
            "CHINEXT" => Self::ChinextSharesOnShenzhenStockExchange,
            "CHIX_CA" => Self::ChiXCanadaAtsLimited,
            "CHIXAU" => Self::ChiXAustralia,
            "CHX" => Self::ChicagoStockExchange,
            "CITIFX" => Self::CitibankCurrencyDealing,
            "CME" => Self::ChicagoMercantileExchange,
            "COMEX" => Self::CommodityExchange,
            "CPH" => Self::CopenhagenStockExchange,
            "CSBONDG" => Self::CreditSuisseGovernmentBondsSmallOrders,
            "CSFBALGO" => Self::CsfbAlgorithmicEngine,
            "CSFX" => Self::CreditSuisseCurrencyDealing,
            "CTDLZERO" => Self::CitadelZeroCommission,
            "DRCTEDGE" => Self::DirectEdgeEcnLlc,
            "DXEDE" => Self::CboeGermany,
            "DXEEN" => Self::CboeEuronext,
            "DXEES" => Self::CboeSpain,
            "DXEIT" => Self::CboeEuropeBVDxeOrderBookItaly,
            "EBS" => Self::ElektronischeBoerseSchweiz,
            "EDGEA" => Self::DirectEdgeEcnEdgea,
            "EDGX" => Self::BatsTradingEdgx,
            "EMERALD" => Self::MiaxEmeraldExchange,
            "ENDEX" => Self::IceEndexFutures,
            "ENEXT.BE" => Self::EuronextBelgium,
            "EUIBFRSH" => Self::InternalFractionalShareVenueForEuStocksAndEtfs,
            "EUIBSI" => Self::IbEuropeanSystematicInternaliser,
            "EUREXUK" => Self::EurexBritishMarketsForLchCrestClearing,
            "FOXRIVER" => Self::FoxRiver,
            "FRACSHARE" => Self::PartnerFractionalShares,
            "FTA" => Self::FinancieleTermijnmarktAmsterdam,
            "FINRA" => Self::Finra,
            "FUNDSERV" => Self::MutualFundHoldingVenue,
            "FWB" => Self::FrankfurterWertpapierboerse,
            "FXSETTLE" => Self::NonStandardSettlementForFx,
            "GEMINI" => Self::IseGemini,
            "GETTEX" => Self::BRseMNchenAg,
            "GETTEX2" => Self::BRseMNchenAgForCblSettlement,
            "GS2FX" => Self::GoldmanSachsCurrencyDealing2,
            "GSFX" => Self::GoldmanSachsCurrencyDealing,
            "HEADLAND" => Self::HeadlandsTechnologies,
            "HEADLANDM" => Self::HeadlandsTechnologiesMunis,
            "HEX" => Self::HelsinkiStockExchange,
            "HKFE" => Self::HongKongFuturesExchange,
            "HSBC2FX" => Self::HsbcCurrencyDealing2,
            "HSBCFX" => Self::HsbcCurrencyDealing,
            "HTD" => Self::HartfieldTitusAndDonnelly,
            "IBAPCFD" => Self::IbCfdDealingAsiaPacific,
            "IBBOND" => Self::InteractiveBrokersBond,
            "IBCMDTY" => Self::InteractiveBrokersCommodity,
            "IBDARK" => Self::IbDarkPool,
            "IBEOS" => Self::IbkrOvernightExchange,
            "IBFX" => Self::IbCurrencyDealing,
            "IBFXCFD" => Self::IbFxCfdDealing,
            "IBIS" => Self::IntegriertesBoersenhandelsUndInformationsSystem,
            "IBKRAM" => Self::InteractiveBrokersAssetManagement,
            "IBKRNOTE" => Self::IbkrNote,
            "IBMETAL" => Self::InternalizedTradingOfMetals,
            "IBUSCFD" => Self::IbCfdDealingUs,
            "IBUSOPT" => Self::IbUsOpt,
            "ICECRYPTO" => Self::IceCryptocurrency,
            "ICEUS" => Self::IceFuturesUsInc,
            "IDEAL" => Self::InteractiveBrokersDealingSystem,
            "IDEALPRO" => Self::IbForexPro,
            "IDEALFX" => Self::IdealCurrencyDealing,
            "IDEM" => Self::ItalianDerivativesMarketMilano,
            "IEX" => Self::InvestorsExchange,
            "IPE" => Self::InternationalPetroleumExchange,
            "IR" => Self::InterestRateRecordingExchange,
            "ISE" => Self::InternationalSecuritiesExchange,
            "ISLAND" => Self::Island,
            "JANE" => Self::JaneStreetExecutionServices,
            "JANEZERO" => Self::JaneStreetZeroCommission,
            "JEFFALGO" => Self::JefferiesAlgorithmicEngine,
            "JPMCBOND" => Self::JpmcCorporateBonds,
            "JPNNEXT" => Self::Japannext,
            "KSE" => Self::KoreaStockExchange,
            "LTSE" => Self::LongTermStockExchange,
            "MATIF" => Self::MarcheATermeDInstrumentsFinanciers,
            "MEFFRV" => Self::MercadoEspanolDeFuturosFinancierosRentaVariableProxy,
            "MEMX" => Self::MembersExchange,
            "MERCURY" => Self::IseMercury,
            "MEXDER" => Self::MercadoMexicanoDeDerivados,
            "MEXI" => Self::MexicoStockExchange,
            "MIAX" => Self::MiamiOptionsExchange,
            "MILLADV" => Self::MillenniumAdvisorsCorporateBonds,
            "MKTAXESS" => Self::MarketaxessCorporates,
            "MONEP" => Self::MarcheDesOptsNegDeLaBourseDeParis,
            "MSFX" => Self::MorganStanleyCurrencyDealing,
            "N.RIGA" => Self::NasdaqRiga,
            "N.TALLINN" => Self::NasdaqTallinn,
            "N.VILNIUS" => Self::AbNasdaqVilnius,
            "NASDAQ" => Self::NationalAssociationOfSecurityDealers,
            "NASDAQBX" => Self::NasdaqOmxBxOptionsExchange,
            "NASDAQOM" => Self::NationalAssociationOfSecurityDealersOptionsMarket,
            "NATIXISFX" => Self::NatixisCurrencyDealing,
            "NITE" => Self::KnightTradingOtcbbAndPinkSheets,
            "NITEZERO" => Self::IbkrRetailZeroCommission,
            "NSE" => Self::NationalStockExchangeOfIndiaLimited,
            "NYBOT" => Self::NewYorkBoardOfTrade,
            "NYMEX" => Self::NewYorkMercantileExchange,
            "NYSE" => Self::NewYorkStockExchange,
            "NYSEFLOOR" => Self::NyseFloor,
            "NYSELIFFE" => Self::NyseLiffeUs,
            "NYSENAT" => Self::NyseNational,
            "OMEGA" => Self::OmegaAts,
            "OMS" => Self::StockholmOptionsMarket,
            "OMXNO" => Self::NorwegianSharesOnOmx,
            "OSE" => Self::OsloStockExchange,
            "OSE.JPN" => Self::OsakaStockExchange,
            "OSL" => Self::OslCryptoExchange,
            "OTCBB" => Self::OtcBulletinBoard,
            "OTCLNKECN" => Self::OtcLinkEcn,
            "OVERNIGHT" => Self::OvernightTrading,
            "PAXOS" => Self::PaxosCryptoExchange,
            "PEARL" => Self::MiaxPearlExchange,
            "PHLX" => Self::PhiladelphiaStockExchange,
            "PINK" => Self::PinkSheets,
            "PRA" => Self::PraqueStockExchange,
            "PSE" => Self::PacificStockExchange,
            "PSX" => Self::NasdaqOmxPsx,
            "PURE" => Self::PureTrading,
            "RBC2FX" => Self::RoyalBankOfCanadaCurrencyDealing2,
            "RBCFX" => Self::RoyalBankOfCanadaCurrencyDealing,
            "RBSFX" => Self::RoyalBankOfScotlandCurrencyDealing,
            "RUSSELL" => Self::ExchangeForRussellIndices,
            "SEHK" => Self::StockExchangeOfHongKong,
            "SEHKNTL" => Self::StockExchangeHongKongNorthboundTradingLink,
            "SEHKSZSE" => Self::HongKongShenzhenStockExchangeNorthboundTradingLink,
            "SFB" => Self::StockholmFondbors,
            "SGX" => Self::SingaporeExchange,
            "SGXCME" => Self::SingaporeExchangeCme,
            "SMFE" => Self::TheSmallExchange,
            "SNFE" => Self::SydneyFuturesExchange,
            "SUMRIDGE" => Self::SumridgePartners,
            "SUMRIDGEM" => Self::SumridgePartnersMunicipalBonds,
            "SWB" => Self::StuttgartWertpapierboerse,
            "TASE" => Self::TelAvivStockExchange,
            "TGATE" => Self::Tradegate,
            "TGHEDE" => Self::TurquoiseGlobalHoldingsEuropeBVGermany,
            "TGHEEN" => Self::TurquoiseGlobalHoldingsEuropeBVEuronext,
            "TGHEES" => Self::TurquoiseGlobalHoldingsEuropeBVSpain,
            "TGHEIT" => Self::TurquoiseGlobalHoldingsBVItaly,
            "THFXCFD" => Self::ThFxCfdDealing,
            "TPLUS1" => Self::TPlusOne,
            "TRADEWEB" => Self::TradewebCorporate,
            "TRADEWEBG" => Self::TradewebGovernment,
            "TSE" => Self::TorontoStockExchange,
            "TSEJ" => Self::TokyoStockExchange,
            "UBS2FX" => Self::UbsCurrencyDealing2,
            "UBSBOND" => Self::UbsCorporateBond,
            "UBSFX" => Self::UbsCurrencyDealing,
            "VALUBOND" => Self::KnightValuebondCorporate,
            "VALUBONDG" => Self::KnightValuebondGovernment,
            "VALUBONDM" => Self::MunicipalBondsOnValuebond,
            "VENTURE" => Self::TsxVentureExchange,
            "VIRTBONDG" => Self::VirtuFinancialGovernmentBonds,
            "VSE" => Self::ViennaStockExchange,
            "WFFX" => Self::WellsFargoForex,
            "WSE" => Self::WarsawStockExchange,
            s => return Err(ParseExchangeError(s.to_owned())),
        })
    }
}

impl ToString for Primary {
    #[allow(clippy::too_many_lines)]
    fn to_string(&self) -> String {
        match *self {
            Self::AmsterdamseEffectenbeurs => "AEB",
            Self::AlphaTradingSystems => "ALPHA",
            Self::AmericanStockExchange => "AMEX",
            Self::ApexEuronext => "APEXEN",
            Self::ApexItaly => "APEXIT",
            Self::AquisExchangeEuropeGermany => "AQEUDE",
            Self::AquisExchangeEuropeEuronext => "AQEUEN",
            Self::AquisExchangeEuropeSpain => "AQEUES",
            Self::AquisExchangeEuropeItaly => "AQEUIT",
            Self::Quadriserv => "AQS",
            Self::Archipelago => "ARCA",
            Self::Arcaedge => "ARCAEDGE",
            Self::AustralianStockExchange => "ASX",
            Self::AsxCentrePoint => "ASXCEN",
            Self::BarclaysGovernmentBonds => "BARCBONDG",
            Self::BatsTradingInc => "BATS",
            Self::BelgianFuturesAmpOptionsExchange => "BELFOX",
            Self::NasdaqOmxBx => "BEX",
            Self::Bloomberg => "BLOOMBERG",
            Self::BolsaDeMadrid => "BM",
            Self::Bond1GovernmentBonds => "BOND1G",
            Self::BondDesk => "BONDDESK",
            Self::BonddeskForUsGovernmentSecurities => "BONDDESKG",
            Self::BondDeskMunicipalBonds => "BONDDESKM",
            Self::GovernmentBondsLargeOrders => "BONDLARGE",
            Self::BostonOptionExchange => "BOX",
            Self::BudapestStockExchange => "BUX",
            Self::LisbonStockExchange => "BVL",
            Self::BorsaValoriDiMilano => "BVME",
            Self::BorsaItalianaEtf => "BVME.ETF",
            Self::BatsYExchange => "BYX",
            Self::CommerzbankAgFrankfurtCurrencyDealing2 => "CBK2FX",
            Self::CommerzbankAgFrankfurtCurrencyDealing => "CBKFX",
            Self::ChicagoBoardOptionsExchange => "CBOE",
            Self::CboeJapanLimited => "CBOE.JPN",
            Self::ChicagoBoardOptionsExchange2 => "CBOE2",
            Self::ChicagoBoardOfTrade => "CBOT",
            Self::CanadianDerivativesExchange => "CDE",
            Self::CboeFuturesExchange => "CFE",
            Self::ChicagoFuturesExchangeTradingAtSettlement => "CFETAS",
            Self::ChinextSharesOnShenzhenStockExchange => "CHINEXT",
            Self::ChiXCanadaAtsLimited => "CHIX_CA",
            Self::ChiXAustralia => "CHIXAU",
            Self::ChicagoStockExchange => "CHX",
            Self::CitibankCurrencyDealing => "CITIFX",
            Self::ChicagoMercantileExchange => "CME",
            Self::CommodityExchange => "COMEX",
            Self::CopenhagenStockExchange => "CPH",
            Self::CreditSuisseGovernmentBondsSmallOrders => "CSBONDG",
            Self::CsfbAlgorithmicEngine => "CSFBALGO",
            Self::CreditSuisseCurrencyDealing => "CSFX",
            Self::CitadelZeroCommission => "CTDLZERO",
            Self::DirectEdgeEcnLlc => "DRCTEDGE",
            Self::CboeGermany => "DXEDE",
            Self::CboeEuronext => "DXEEN",
            Self::CboeSpain => "DXEES",
            Self::CboeEuropeBVDxeOrderBookItaly => "DXEIT",
            Self::ElektronischeBoerseSchweiz => "EBS",
            Self::DirectEdgeEcnEdgea => "EDGEA",
            Self::BatsTradingEdgx => "EDGX",
            Self::MiaxEmeraldExchange => "EMERALD",
            Self::IceEndexFutures => "ENDEX",
            Self::EuronextBelgium => "ENEXT.BE",
            Self::InternalFractionalShareVenueForEuStocksAndEtfs => "EUIBFRSH",
            Self::IbEuropeanSystematicInternaliser => "EUIBSI",
            Self::EurexBritishMarketsForLchCrestClearing => "EUREXUK",
            Self::FoxRiver => "FOXRIVER",
            Self::PartnerFractionalShares => "FRACSHARE",
            Self::FinancieleTermijnmarktAmsterdam => "FTA",
            Self::Finra => "FINRA",
            Self::MutualFundHoldingVenue => "FUNDSERV",
            Self::FrankfurterWertpapierboerse => "FWB",
            Self::NonStandardSettlementForFx => "FXSETTLE",
            Self::IseGemini => "GEMINI",
            Self::BRseMNchenAg => "GETTEX",
            Self::BRseMNchenAgForCblSettlement => "GETTEX2",
            Self::GoldmanSachsCurrencyDealing2 => "GS2FX",
            Self::GoldmanSachsCurrencyDealing => "GSFX",
            Self::HeadlandsTechnologies => "HEADLAND",
            Self::HeadlandsTechnologiesMunis => "HEADLANDM",
            Self::HelsinkiStockExchange => "HEX",
            Self::HongKongFuturesExchange => "HKFE",
            Self::HsbcCurrencyDealing2 => "HSBC2FX",
            Self::HsbcCurrencyDealing => "HSBCFX",
            Self::HartfieldTitusAndDonnelly => "HTD",
            Self::IbCfdDealingAsiaPacific => "IBAPCFD",
            Self::InteractiveBrokersBond => "IBBOND",
            Self::InteractiveBrokersCommodity => "IBCMDTY",
            Self::IbDarkPool => "IBDARK",
            Self::IbkrOvernightExchange => "IBEOS",
            Self::IbCurrencyDealing => "IBFX",
            Self::IbFxCfdDealing => "IBFXCFD",
            Self::IntegriertesBoersenhandelsUndInformationsSystem => "IBIS",
            Self::InteractiveBrokersAssetManagement => "IBKRAM",
            Self::IbkrNote => "IBKRNOTE",
            Self::InternalizedTradingOfMetals => "IBMETAL",
            Self::IbCfdDealingUs => "IBUSCFD",
            Self::IbUsOpt => "IBUSOPT",
            Self::IceCryptocurrency => "ICECRYPTO",
            Self::IceFuturesUsInc => "ICEUS",
            Self::InteractiveBrokersDealingSystem => "IDEAL",
            Self::IbForexPro => "IDEALPRO",
            Self::IdealCurrencyDealing => "IDEALFX",
            Self::ItalianDerivativesMarketMilano => "IDEM",
            Self::InvestorsExchange => "IEX",
            Self::InternationalPetroleumExchange => "IPE",
            Self::InterestRateRecordingExchange => "IR",
            Self::InternationalSecuritiesExchange => "ISE",
            Self::Island => "ISLAND",
            Self::JaneStreetExecutionServices => "JANE",
            Self::JaneStreetZeroCommission => "JANEZERO",
            Self::JefferiesAlgorithmicEngine => "JEFFALGO",
            Self::JpmcCorporateBonds => "JPMCBOND",
            Self::Japannext => "JPNNEXT",
            Self::KoreaStockExchange => "KSE",
            Self::LongTermStockExchange => "LTSE",
            Self::MarcheATermeDInstrumentsFinanciers => "MATIF",
            Self::MercadoEspanolDeFuturosFinancierosRentaVariableProxy => "MEFFRV",
            Self::MembersExchange => "MEMX",
            Self::IseMercury => "MERCURY",
            Self::MercadoMexicanoDeDerivados => "MEXDER",
            Self::MexicoStockExchange => "MEXI",
            Self::MiamiOptionsExchange => "MIAX",
            Self::MillenniumAdvisorsCorporateBonds => "MILLADV",
            Self::MarketaxessCorporates => "MKTAXESS",
            Self::MarcheDesOptsNegDeLaBourseDeParis => "MONEP",
            Self::MorganStanleyCurrencyDealing => "MSFX",
            Self::NasdaqRiga => "N.RIGA",
            Self::NasdaqTallinn => "N.TALLINN",
            Self::AbNasdaqVilnius => "N.VILNIUS",
            Self::NationalAssociationOfSecurityDealers => "NASDAQ",
            Self::NasdaqOmxBxOptionsExchange => "NASDAQBX",
            Self::NationalAssociationOfSecurityDealersOptionsMarket => "NASDAQOM",
            Self::NatixisCurrencyDealing => "NATIXISFX",
            Self::KnightTradingOtcbbAndPinkSheets => "NITE",
            Self::IbkrRetailZeroCommission => "NITEZERO",
            Self::NationalStockExchangeOfIndiaLimited => "NSE",
            Self::NewYorkBoardOfTrade => "NYBOT",
            Self::NewYorkMercantileExchange => "NYMEX",
            Self::NewYorkStockExchange => "NYSE",
            Self::NyseFloor => "NYSEFLOOR",
            Self::NyseLiffeUs => "NYSELIFFE",
            Self::NyseNational => "NYSENAT",
            Self::OmegaAts => "OMEGA",
            Self::StockholmOptionsMarket => "OMS",
            Self::NorwegianSharesOnOmx => "OMXNO",
            Self::OsloStockExchange => "OSE",
            Self::OsakaStockExchange => "OSE.JPN",
            Self::OslCryptoExchange => "OSL",
            Self::OtcBulletinBoard => "OTCBB",
            Self::OtcLinkEcn => "OTCLNKECN",
            Self::OvernightTrading => "OVERNIGHT",
            Self::PaxosCryptoExchange => "PAXOS",
            Self::MiaxPearlExchange => "PEARL",
            Self::PhiladelphiaStockExchange => "PHLX",
            Self::PinkSheets => "PINK",
            Self::PraqueStockExchange => "PRA",
            Self::PacificStockExchange => "PSE",
            Self::NasdaqOmxPsx => "PSX",
            Self::PureTrading => "PURE",
            Self::RoyalBankOfCanadaCurrencyDealing2 => "RBC2FX",
            Self::RoyalBankOfCanadaCurrencyDealing => "RBCFX",
            Self::RoyalBankOfScotlandCurrencyDealing => "RBSFX",
            Self::ExchangeForRussellIndices => "RUSSELL",
            Self::StockExchangeOfHongKong => "SEHK",
            Self::StockExchangeHongKongNorthboundTradingLink => "SEHKNTL",
            Self::HongKongShenzhenStockExchangeNorthboundTradingLink => "SEHKSZSE",
            Self::StockholmFondbors => "SFB",
            Self::SingaporeExchange => "SGX",
            Self::SingaporeExchangeCme => "SGXCME",
            Self::TheSmallExchange => "SMFE",
            Self::SydneyFuturesExchange => "SNFE",
            Self::SumridgePartners => "SUMRIDGE",
            Self::SumridgePartnersMunicipalBonds => "SUMRIDGEM",
            Self::StuttgartWertpapierboerse => "SWB",
            Self::TelAvivStockExchange => "TASE",
            Self::Tradegate => "TGATE",
            Self::TurquoiseGlobalHoldingsEuropeBVGermany => "TGHEDE",
            Self::TurquoiseGlobalHoldingsEuropeBVEuronext => "TGHEEN",
            Self::TurquoiseGlobalHoldingsEuropeBVSpain => "TGHEES",
            Self::TurquoiseGlobalHoldingsBVItaly => "TGHEIT",
            Self::ThFxCfdDealing => "THFXCFD",
            Self::TPlusOne => "TPLUS1",
            Self::TradewebCorporate => "TRADEWEB",
            Self::TradewebGovernment => "TRADEWEBG",
            Self::TorontoStockExchange => "TSE",
            Self::TokyoStockExchange => "TSEJ",
            Self::UbsCurrencyDealing2 => "UBS2FX",
            Self::UbsCorporateBond => "UBSBOND",
            Self::UbsCurrencyDealing => "UBSFX",
            Self::KnightValuebondCorporate => "VALUBOND",
            Self::KnightValuebondGovernment => "VALUBONDG",
            Self::MunicipalBondsOnValuebond => "VALUBONDM",
            Self::TsxVentureExchange => "VENTURE",
            Self::VirtuFinancialGovernmentBonds => "VIRTBONDG",
            Self::ViennaStockExchange => "VSE",
            Self::WellsFargoForex => "WFFX",
            Self::WarsawStockExchange => "WSE",
        }
        .to_owned()
    }
}
